Fix to SBT 0.13.6
When running a community build with Java 8, this project failed with:

```
[sbt-republish:error] error: error while loading CharSequence, class file '/usr/lib/jvm/jdk1.8.0_05/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[sbt-republish:error] (bad constant pool tag 15 at byte 1501)
[sbt-republish] [error] Type error in expression
[sbt-republish] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

I can provoke the same error by using SBT 0.12.4 with Java 8:

```
% sbt -sbt-version 0.12.4
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)
```

The underlying error was fixed when Scala 2.10.1 added support for classfiles containing `MethodHandle`s in the constant pool.

This commit adds a build.properties to pin down the version of SBT.
I'm not sure if this will solve the community build problem, but
it is a best practice in any case. I've updated to a newer sbt-osgi
version to accomodate that change.